### ISSUE TITLE
FullCalendar 5.4.0

### ISSUE THREAD

**Issue by melloware** [mherrmann/fullcalendar-rightclick#23]
Do you mind updating this plugin for FullCalendar 5.4.0 please?

**Comment by mherrmann** [comment]
Haha sure I'll spend my spare time doing work for you.

**Comment by melloware** [comment]
> Haha sure I'll spend my spare time doing work for you.

Haha.  In 25 years doing open source this is the first time I have seen an author **troll** his own project!

A more appropriate answer would have been "I currently do not have time to dedicate to this project, but if someone provides a PR I will gladly review and merge it".   But I see you chose a different route...
