### ISSUE TITLE
taphold, long press

### ISSUE THREAD

**Issue by drago1** [mherrmann/fullcalendar-rightclick#4]
Hi,
I don't know how to contact you, so I am writing here.
Is there possibility  to provide same functionality for something like "taphold"(jquery), "press"(hammer.js) on event.
Thanks

**Comment by mherrmann** [comment]
Hi Drago,

I feel it's beyond the scope of this library but if you look at the code I'm pretty sure it would be easy for you to adapt it for "taphold" and "press".

Cheers,
Michael

**Comment by drago1** [comment]
thanks, honestly I already tried modify your code, but i have problems at the begging. I got error after page load:
TypeError: View is undefined
View = View.class || View;

can you help  me to solve this problem?
