### ISSUE TITLE
Right Click on Selection Area

### ISSUE THREAD

**Issue by acidnine** [mherrmann/fullcalendar-rightclick#9]
I noticed that right clicking on a selection or any day in the row of a selection (default full calendar view) wouldn't trigger... Modifying https://github.com/mherrmann/fullcalendar-rightclick/blob/master/fullcalendar-rightclick.js#L34 to be '.fc-bgevent-skeleton, .fc-highlight-skeleton' seems to have solve that particular piece for 3.0.0.

**Comment by mherrmann** [comment]
Thank you very much. I have incorporated your suggestion. It's part of the latest release, v1.8.
